---
name: NX run parallel commands

inputs:
  main-jobs:
    type: string
    required: false
  agent-jobs:
    type: string
    required: false

runs:
  using: composite
  steps:
    - name: Run parallel jobs
      run: |
        execute-parallel-jobs "${{ inputs.main-jobs }}" "${{ inputs.agent-jobs }}"
      shell: bash
