---
name: NX run parallel commands

inputs:
  main-jobs:
    type: string
    required: false
  agent-jobs:
    type: string
    required: false

runs:
  using: composite
  steps:
    - name: Run parallel jobs
      run: |
        main_jobs="${{ inputs.main-jobs }}"
        printf 'Executing jobs on main:\n\n'
        echo "$main_jobs"
        printf '\n\n'

        agent_jobs="${{ inputs.agent-jobs }}"
        printf 'Executing jobs on agents:\n\n'
        echo "$agent_jobs"
        printf '\n\n'

      shell: bash
